#!/bin/zsh

autoload -U zmv

TARGET=vendor/assets/stylesheets

rm -rf $TARGET
cp -rf ../animate.sass/stylesheets $TARGET

for file in `ls $TARGET/**/*.scss`
do
  echo "processing $file..."
  sass-convert -i -T Sass $file
  zmv $file '$f:gs/scss/sass'
done
